# Generated by Django 4.2.7 on 2023-11-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
