# Generated by Django 4.2.7 on 2023-11-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_etapaproyecto_pago_ordendecompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('causa', models.TextField(blank=True, null=True)),
                ('tipo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('facturado', 'facturado')], max_length=100, null=True)),
                ('fecha_pago_cheque', models.DateField(blank=True, null=True)),
                ('datos_cheque', models.TextField(blank=True, null=True)),
                ('costo_cheque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etapa_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibidos', to='home.etapaproyecto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to='home.proveedor')),
            ],
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='pagos',
            field=models.ManyToManyField(related_name='ordenes_compra', to='home.pagos'),
        ),
    ]
