# Generated by Django 4.2.7 on 2023-11-07 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_servicio_costo_servicio_fecha_contratacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0.00),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_contratacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]

    migrations.AlterField(
    model_name='servicio',
    name='costo',
    field=models.DecimalField(decimal_places=2, max_digits=10, default=0.00),
),

